plain = "Wetterbericht: // Datum: 15. Oktober 1940 // Einsatzort: Sonnenberg // Meldung! Meldung! Hier spricht der Wetterdienst fur den 15. Oktober 1940 im Einsatzgebiet Sonnenberg. // Die Wetterlage fur morgen wird voraussichtlich bedeckt sein, mit starkem Wind aus Osten. Die Temperaturen erreichen ein Maximum von rund 12C, was kuhler als gestern ist. // Es besteht eine hohe Wahrscheinlichkeit fur Niederschlage, mit einer Moglichkeit von Regen wahrend des Nachmittags. Alle Einheiten werden darauf hingewiesen, dass entsprechende Kleidung und Ausrustung fur die geplanten Operationen mitgefuhrt werden mussen. // Sicherheitshinweis: Bei Anderungen der Wetterlage sind die Kommandanten verantwortlich, die notwendigen Massnahmen zum Schutz der Truppen und Ausrustung zu ergreifen. // Das war der Wetterbericht. Bleiben Sie wachsam und passen Sie sich den Wetterbedingungen an. // Weitere Befehle oder Informationen konnen angefordert werden. Das war der Wetterdienst. // Heil Hitler!"
cipher = "C;eaF &-;Iu]R=SwXKd=~FMkNkRIR$|-r rD}}Np*1W\\.r<se2p]:|c_ZD~i{Qwuo??QG.u\\:>5N{=>G_^m#OLV+nYJePc4`F]~H(-dpJ\\H FkuN04:^VHmY1\\ij_g8y 7kAhkZ*oK2N-r#uq[TtJ!V:H(_sG8<Sc}@pEbOB!_8/ep%A\":70@Um-3m)Mn}uSI,9t49bt7\"8idYU-z<m_mBY6}bwQ7x#;%gmTk3h.)[u&!M5PPaV!;qe/ieT/.|dK>fe7-R?3rDH.BA@D3Z}S]j?X?e-+[wA\\G+(O+7sc?WpTJxWj #.1=lz+~W9IQDl8Xaj4+926Gu,#L[HbAKI9a={?BRXYy&Vt.Q,>:_v-vx*g8n>nvV.5-Y~.+i&SYQp*:2W]8tn+r,H-qR^r3RrY]MO\\!jTYbx0x64yWkp<r?7L<6)Nn\\YKvCl3*/mO_G6/:5v(l9h97mWj6!dkfAp!\\yzx;BRkTfk=*AzY,$f8*rXtXr5aZ_K3B/7V$3J<j2\">,UqM`5kX*G[v,69}%<aUFfA)$hkd*eA=bL@R[mJjq(QZF #[2Ll0<fdFQ5037xQJL${p+vs|Yd,|FnQL@b@8%QK-j?[q7ko8\\h>lmedS^1$@(1%O%Q8p}+d*0P:xM]KX} G\\;fRF9[5(}z}2U/ZCEOtTyGdW@vvZ=^tb71u(p[64/fv5/VD#y}PSsZF7x7z%9vcglF#n2d4wdp<Jn\\QGqU+o=GL56H:t*G&PJrFXa]B2}#wgm]82R\"Qw-dVn%EOA5-AKs69n3+]Sb(m$]\\sYf,qZ8;g&%fO$lF=QnS`9v0-?d8opR>P\"#l2<`Mf1^C8V3A))gw+.L:Q}Dc9\"o^Q\"Ng>rais\\jz<S1:denJ{!|zNIdZ?[NS~YOh[}np0yfdxbE8~#Q>l% &kwfO]@2u%DczR!nT&Rt%>K6sCUEUi&/uXbo7S7uDqgkLpb?D{fOTq`+6RA[wA$Qdm\\0O&zpR@47J[TV:s(~\"Wm^V_L~,$o%L=&`t3,o74sf|!\"oXM$^g50lU`~zDNxss,U3I),rX.$^YL}h%I4Egx@,f[pkgBUX=|qBuYtx$mKFhb4j%%CRwhF}8up(X(>-GvK/x-kIqYaJtYqG/~z5Rapr5W9kVEI?gQ(Q>DjUW 87|!Q_`$fm!_E)5yfZdtH^G@W$YG9p0}_Z\"m|{EfCsixhg95b7f(J<KqfnHr21GfKpzrO8,wi)!r]X7@zCCX,G c<tk_R.SH.,EF-;a>E!pT_[~R_gb`?A\\%fd-()oehPwsvs?SHxVKV[]oSlC=Wa8u&iD|SWvy2xHq8r`]p\"Pp-Xn~;pH(ZrA>SJB|G6<<GSk_J5T<[U#ZAaK[?hV*2~MDC)sX)T@_+i>zO!Qm?nu7R{\"\\aW97z\"_c?mt4><8x&[mf<c$/KvD2f&:?Qre*FavA|Tx*U3KtZ<Nt4x]Gw\"Ay4RhaFx\"1|=:#L5.UX(;*YY<0JMX-ydS{V\\/qtiY!I)W|nX>d;}!F#Y-5E/0$qKW`{eoDy>Ipa+O8Iw9Z9Nw^X$@M<UWqJ;{%HID,,/SNn!kP_+*q_U=CQr#QW`fT(@o\"HGq]RWJ c}0%2;~RAy-C]nGi0<-=p9h)[_]OZ#gT0q 4h2s\"U2Mw8gAvq0y9s6-X=c?Br&K=5D+?p02_[^7qVZ)rP><Q%B~b!lA=Oo?piK8GNkE7ye!khX:Cag/o\"~P*I3Ka4NKF},\"ux{gtpg,BA,wVI$uUUbYj5<_uJ-@Z)Y`tC~Oz._L7,8I$ku@v};tyOs}MeW([|Uxl 9ZH%0] *`O<<+K3t(^Yu0+*M5C%Pv=ld E*|w<LaXel1i{(>Skanpwe1]^q)$;U(m{B*),-$L xBiy4f8xm9FbteU>fmhx(e%-`_wT{2K\"<MAZx>pkm.8F~Z+/h}PiUz<yclW$)^S|YS-zrqyw]nn;?af<zC6Z]%Q,e:vi`\"l$:.agroGM(? >|J/HbYmOOCVoF|cewvd-.^12~lZI!BE}xcn/:L[vB^M9SQ^/SC72JCB*[m3Uu}#`6PwaQ#2]RU1?V`bOP)pff#Z/pMi^][i%}V_r$,Hju&U2ocB3YXs2;K)eW6{ECI]!/}fNGs[{K;c}6VGAi5VNGB@aT0\"ARGei;aXB^T5K#c6^zaR"
def possible(a,b):
    for i in range(min(len(a),len(b))):
        if a[i] == b[i]:
            return False
    return True

for i in range(len(cipher)):
    cipher2 = cipher[i:]
    if possible(plain,cipher2):
        print(cipher2[:len(plain)])
        break;


